theme = "PaperMod"
baseURL = "https://seddspace.pages.dev"
languageCode = "zh-tw"
title = "Sedd · SEO"

[params]
  defaultTheme        = "auto"
  disableThemeToggle  = false
  description         = "SEO 策略・技術優化・搜尋排名"
  ShowReadingTime     = true
  ShowShareButtons    = false
  ShowPostNavLinks    = true
  ShowBreadCrumbs     = false
  ShowCodeCopyButtons = true
  comments            = false

  # Required to trigger home_info.html partial
  [params.homeInfoParams]
    Title = ""

[[menu.main]]
  name   = "文章"
  url    = "/posts/"
  weight = 10

[[menu.main]]
  name   = "關於"
  url    = "/about/"
  weight = 20

[[menu.main]]
  name   = "標籤"
  url    = "/tags/"
  weight = 30
